//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ForceModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ForceMode));
		L.RegVar("Force", get_Force, null);
		L.RegVar("Acceleration", get_Acceleration, null);
		L.RegVar("Impulse", get_Impulse, null);
		L.RegVar("VelocityChange", get_VelocityChange, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.ForceMode>.Check = CheckType;
		StackTraits<UnityEngine.ForceMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.ForceMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.ForceMode), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Force(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ForceMode.Force);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Acceleration(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ForceMode.Acceleration);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Impulse(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ForceMode.Impulse);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VelocityChange(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ForceMode.VelocityChange);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ForceMode o = (UnityEngine.ForceMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

